### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by mlissner**

### CODE REVIEW

**Comment by konklone** [comment]
Believe it or not, I thought about this, and it is an intentional misspelling. I prefer "leafs" when abbreviating the phrase "leaf nodes".

**Comment by mlissner** [comment]
I was afraid of that. You go too far, sir. Too far.

**Comment by mlissner** [comment]
Now I'm realizing you also used wolves in one of your metaphors, but I can't remember if/how you pluralized that.

**Comment by konklone** [comment]
I'm very deliberate in how I speak about wolf nodes.

**Pull request closed without merging**
